# Generated by Django 4.1.7 on 2023-11-06 21:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RealEstateListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("listing_title", models.CharField(max_length=255)),
                ("street", models.CharField(blank=True, max_length=255, null=True)),
                ("district", models.CharField(blank=True, max_length=255, null=True)),
                ("city", models.CharField(blank=True, max_length=255, null=True)),
                ("voivodeship", models.CharField(max_length=255)),
                ("price", models.IntegerField()),
                ("price_per_sqm", models.FloatField()),
                ("rooms", models.IntegerField()),
                ("area", models.FloatField()),
                ("url", models.URLField()),
            ],
        ),
    ]
